### ISSUE TITLE
maclan + port

### ISSUE THREAD

**Issue by brjppru** [hardware/rainloop#13]
docker network create -d macvlan --subnet=192.168.88.0/24 --gateway=192.168.88.1 -o parent=enp3s0 net88

docker run --restart unless-stopped --net=net88 --ip=192.168.88.101 -p 80:8888 --name rainloop hardware/rainloop

no answer on 192.168.88.101:80 -> only on 192.168.101:8888

**Comment by hardware** [comment]
Can you explain a bit better your problem ?

**Comment by brjppru** [comment]
if I run the container as an application

docker run -it -p 80: 8888 --name brjrain hardware / rainlup

then the call on port 80 works on the host where the docker is launched

if I create a separate network that is routed to my local network, the container does not respond on port 80, but there is a response to port 8888

docker run --restart unless-stopped - net = net88 --ip = 192.168.88.101 -p 80: 8888 --name rainloop hardware / rainloop

**Comment by hardware** [comment]
Not related to Rainloop, I close this issue. Please, report your issue on moby repository.
