### ISSUE TITLE
`docker logs rainloop` is empty

### ISSUE THREAD

**Issue by AndrewSav** [hardware/rainloop#14]
Hey, looking at this container as part of `mailserver` installation from the other repository. There seems to be no logs whatsoever for rainloop which is making troubleshooting difficult. `docker logs rainloop` is empty - not a single line.

Am I doing something wrong?

**Comment by Franselbaer** [comment]
Yes, that's correct. This is due to the s6-supervise daemon. But mostly it isn't really necessary. Mostly you can consider this as blackbox and for stuff like https you mostly put a nginx in front of where you can pull the logs from.

**Comment by AndrewSav** [comment]
What do you mean It's not necessary? I'm getting 503 on nginx, and I have no idea why. (apparently rainloop fails to start for some reason) and I have no way to troubleshoot. How do I troubleshoot then? @hardware @Franselbaer

**Comment by hardware** [comment]
https://github.com/hardware/rainloop/blob/master/rootfs/etc/nginx/nginx.conf#L15

Any unix command can help you :

```
ps aux
tail -f /tmp/ngx_error.log
...etc
```

**Comment by Franselbaer** [comment]
Overseen.... 🙄🤭 Maybe its better to throw this to stdout as the standard in docker is..... I can do and send a pull request tomorrow...

**Comment by hardware** [comment]
Yes you can do that.

```nginx
error_log /dev/stdout warn;
```
And fix permissions in run.sh
```
chmod o+w /dev/stdout
```

But this is not the purpose of this image and this will hide the real problems. HTTP request logs must be managed by a reverse proxy, not by this docker image.

**Comment by Franselbaer** [comment]
And @AndrewSav ? Please see https://github.com/hardware/rainloop/pull/15.
Is this what you wanted?

**Comment by AndrewSav** [comment]
@Franselbaer thank you very much for this, your help is really appreciated. I opened this issue 20 days ago, so I moved onto other things since then. I will make sure to comment here later when I revisit the issue. It does _look_ like what I wanted ;) Thank you again for your help.

**Comment by Franselbaer** [comment]
You're welcome.

**Comment by AndrewSav** [comment]
@Franselbaer I was not able to make it work. All I get in the logs is:

```
root@mail:~/mailserver# docker logs f95649fec9eb -f
[INFO] Logging to stdout activated
```

And nothing else is coming through. Not sure what I did wrong. I'm expecting to see web request from the browser as I'm using the rainloop website.

**Comment by AndrewSav** [comment]
Okay never mind, I see what you did. The access log is always off and error log won't receive 404. Since I do not actually have an issue any longer I cannot attest how useful this is for real world troubleshooting.  I tried to make it produce a error but I could not. Once again, thank you for your work.
