### ISSUE TITLE
php-net-sieve not installed

### ISSUE THREAD

**Issue by r3pek** [hardware/rainloop#16]
Can we please get this module installed so that the sieve support works within RainLoop?

**Comment by hardware** [comment]
Sieve works out-of-box with this docker image and `php-net-sieve` doesn't exit in alpine repository : 

https://pkgs.alpinelinux.org/packages?page=1&repo=community&branch=v3.7&name=php7-%2A&arch=x86_64

**Comment by r3pek** [comment]
It's not working on my setup (which works with roundcube).
Maybe it could be a rainloop issue? I do see the login on the logs (managesieve side), but nothing ever shows up on the UI on RainLoop

**Comment by hardware** [comment]
Can you post some screenshot of your problem ?

Sieve settings : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration#sieve-configuration-

**Comment by r3pek** [comment]
![image](https://user-images.githubusercontent.com/3050556/41859759-c94cebf2-7894-11e8-9442-485ceb1ce963.png)
![image](https://user-images.githubusercontent.com/3050556/41859690-9b9f2026-7894-11e8-8677-cb952e706f53.png)
Settings are as mentioned, but if you still want a screenshot, I'll post it.

**Comment by hardware** [comment]
Rainloop can't parse any rule created with another sieve tool. Try to create a new filter with rainloop.

**Comment by r3pek** [comment]
OK, got it. Too bad that it still doesn't support all the sieve features (like multiple scripts). I'll recreate all of them by hand.
