### ISSUE TITLE
Allowed memory exausted

### ISSUE THREAD

**Issue by r3pek** [hardware/rainloop#17]
Looks like the configured allowed memory for PHP/FastCGI is too low. I'm getting this error when I try to open a folder with 67k emails (6k conversations).

2018/06/25 14:47:06 [error] 19#19: *1611 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /rainloop/rainloop/v/1.12.0/app/libraries/MailSo/Mail/MailClient.php on line 1601" while reading response header from upstream, client: 10.0.1.154, server: , request: "GET /?/Ajax/&q[]=/_PBu-IzM-T8d3d4K0VWtjVjpV-pDQDvmq_rA6gnfC2eTTO4UIAgpb7epY4AjvHy4Y-bTxk0pCrvz3y0c5tggDbR9bPG4JeJI1HbwlawW04sruUvw41Q-PA4LBI_BF_RemHESzl6tyextJBqxcn4V4oGqRC1FcYf2f0sVd0HCxC8y3korhL3N6ISKFKmyfdSH1EZiybKROhSqYOxuFEShZLtbkXRXDYmApRRAcFO-kXjCq64laES_V1LKC3s_1z_j6CHd0Y_iP6ADpidSk1hFskoNvgwcpK8weXXvRkeURSLC35myPDOOz96SIQW4rRA9ytU6QHVQ3pR8/MessageList/&q[]=/QWJlcnRvIGF0JkFPay0gZGUgTWFkcnVnYWRhADAANTAAAGZiNDk1MDA1ZjY1NDVhN2RhOTU2YWY3NzQ5NzJiOTg5ADkwMjFjOGVmMjkzNWRiODkwODA3MmI5YzcyM2Y5NzJlAAAxAA HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "webmail.example.com", referrer: "https://webmail.example.com/"

**Comment by hardware** [comment]
Clone this repository, add `php_admin_value[memory_limit] = <MEMORY_LIMIT>` to **rootfs/etc/php7/php-fpm.conf**, replace `<MEMORY_LIMIT>` with an adequate value and rebuild `docker build -t rainloop .`

If it works, I will add a new memory limit environment variable to this docker image.

**Comment by hardware** [comment]
I added a memory limit env variable : https://github.com/hardware/rainloop#environment-variables

**Comment by r3pek** [comment]
Thanks mate. It works and solved the problem! :)
