### ISSUE TITLE
Domains List is empty

### ISSUE THREAD

**Issue by vizv** [hardware/rainloop#2]
Domains not get listed on `https://example.com/?admin#/domains` due to https://github.com/RainLoop/rainloop-webmail/issues/1109.

Patch for version 1.10.3.151 may be applied with:

``` sh
sed -i 's#.*GLOB_BRACE);#$aList = @\\array_diff(\\scandir($this->sDomainPath), array('"'"'.'"'"', '"'"'..'"'"'));#g' \
    /rainloop/rainloop/v/1.10.3.151/app/libraries/RainLoop/Providers/Domain/DefaultDomain.php
```

**Comment by hardware** [comment]
Fixed in the latest docker hub build ;)
