### ISSUE TITLE
BUG: Can't upload any attachments over ~500kB

### ISSUE THREAD

**Issue by adshrc** [hardware/rainloop#4]
Hi,

i found a bug, where you get an "unkonwn error" if you try to upload attachments over ~500kB.  Fortunately, it's only a small misconfiguration in `/etc/nginx/nginx.conf`, where you have to add `client_max_body_size 32M` in the `server {..}` directive.

Additionally, the php upload values should also be increased, since 2 MB are not enough, even for a simple .jpg.

I use:

```
upload_max_filesize=25M;
post_max_size=32M;
```

I hope this will be fixed in the next commit 👍

**Comment by hardware** [comment]
Fixed in ef78efd

Wait for dockerhub build and tell me if your problem is solved :)
