### ISSUE TITLE
`chown` in `run.sh`: bad performance and potential security gap

### ISSUE THREAD

**Issue by DrMurx** [hardware/rainloop#9]
The `chown` being done at https://github.com/hardware/rainloop/blob/master/run.sh#L2 is rather inefficient. Most of the targeted directories are part of the base image, so the `chown` makes the overlayfs to create a copy of those file in the container's floating top-layer.

While I would understand that `/var/log` needs to be owned by the user/group, I question this already for `/tmp` (that should be sticky anyway), and I eventually don't see the reason for changing the ownership of all PHP sources and the configuration directories. In fact, it makes any web service unsafer if sources and configuration belong to the same UID as the running service.

So I'd suggest to replace this line like this:
```sh
chown -R $UID:$GID /rainloop/data /var/log
```

**Comment by hardware** [comment]
`CHMOD` is needed for this directories :

* /rainloop
* /services
* /var/log
* /var/lib/nginx

because the PID 1 process (init process) is the rainloop user (`$UID` / `$GID` variables) :

```
PID   USER     TIME   COMMAND
    1 991       0:00 /bin/s6-svscan /services
    8 991       0:00 s6-supervise nginx
    9 991       0:00 s6-supervise php
   10 991       0:00 {php-fpm7} php-fpm: master process (/etc/php7/php-fpm.conf)
   11 991       0:00 nginx: master process nginx
   12 991       0:00 nginx: worker process
   13 991       0:00 nginx: worker process
   14 991       0:00 nginx: worker process
   15 991       0:00 nginx: worker process
   16 991       0:00 nginx: worker process
   17 991       0:00 nginx: worker process
   18 991       0:00 nginx: worker process
   19 991       0:00 nginx: worker process
   20 991       0:00 {php-fpm7} php-fpm: pool www
   21 991       0:00 {php-fpm7} php-fpm: pool www
```

But I removed some useless directories :

* /etc/nginx
* /etc/php7
* /tmp 

Thank you for pointing this out.

**Comment by DrMurx** [comment]
Can you point out why `/services` and `/rainloop` needs to be owned by the rainloop user? As far as I understand it, `s6-svscan` should be perfectly fine with root-owned files in `/service` as long as they're readable. In a similar way, the PHP sources must of course be readable by the `nginx` and `php-fpm` processes, but not owned or writable (except `/rainloop/data`)

**Comment by hardware** [comment]
> Service directories describe the way services are launched. Once they are designed, they have little reason to change on a given machine. They can theoretically reside on a read-only filesystem - for instance, the root filesystem, to avoid problems with mounting failures.

But :

> However, two subdirectories - namely supervise and event - of every service directory need to be writable.

Source : https://skarnet.org/software/s6/servicedir.html

Rainloop : https://www.rainloop.net/docs/permissions/

**Comment by DrMurx** [comment]
I get the thing with `s6-svscan`. 

But for the rainloop sources, I think the docs recommend the chown to allow "automated source upgrades", as seen here https://www.rainloop.net/docs/upgrade/

However, in a docker environment, the container should be as "immutable" as possible and updates shouldn't be done in a running container because that way they are not persisted (ie. recreating the container would bring up an outdated version again). 

In docker, updates are better done by releasing and deploying a new image. Therefore, the sources don't require being writable.

**Comment by hardware** [comment]
Ok i test with `/rainloop/data`, if everything works correctly, I push this modification.

**Comment by hardware** [comment]
@DrMurx Thanks ;)
